version: "3.2"

services:
  couchdb:
    container_name: couchdb
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
      - COUCHDB_SECRET
    image: couchdb:3.0.0
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - 5984:${COUCHDB_PORT}
    restart: always
    volumes:
      - type: volume
        source: couchdb-data
        target: /opt/couchdb/data