version: "3.2"

services:

  couchdb:
    container_name: couchdb
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
      - COUCHDB_SECRET
    image: couchdb:3.0.0
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - ${COUCHDB_PORT}:${COUCHDB_PORT}
    restart: always
    volumes:
      - type: volume
        source: couchdb-data
        target: /opt/couchdb/data

  ui:
    container_name: ui
    environment:
      - UI_PORT
      - IN_CONTAINER
      - NODE_ENV=${NODE_ENV}
      - API_HOST=${COUCHDB_HOST}
      - API_PORT=${COUCHDB_PORT}
      - API_USER=${COUCHDB_USER}
      - API_PASSWORD=${COUCHDB_PASSWORD}
    build:
      context: .
      dockerfile: ui/Dockerfile
      args:
        - IN_CONTAINER=${IN_CONTAINER}
    depends_on:
      - couchdb
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - ${UI_PORT}:${UI_PORT}


volumes:
  couchdb-data:
    driver: local
