version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy_demo:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only: master

  on-pull-request-update:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - unit-test:
          requires:
            - build
          filters:
            branches:
              ignore: master

jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/skilltag
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run: npm run build

  unit-test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/skilltag
    steps:
      - attach_workspace:
          at: .
      - run: ls -la
      - run: npm run test:unit
