version: 2.1

orbs:
  # heroku: circleci/heroku@0.0.10

workflows:
  # heroku_deploy_demo:
  #   jobs:
  #     - heroku/deploy-via-git:
  #         filters:
  #           branches:
  #             only: master

  on-pull-request-update:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - unit-test:
          requires:
            - build
          filters:
            branches:
              ignore: master

jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/skilltag
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run: yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run: yarn run build

  unit-test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/skilltag
    steps:
      - attach_workspace:
          at: .
      - run: yarn run test:unit
