version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy_demo:
    jobs:
      - heroku/deploy-via-git # Use the pre-configured job, deploy-via-git
          filters:
            branches:
              ignore: sequential-branch-filter

